# Generated by Django 4.0.4 on 2022-09-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsGRBL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='titulo')),
                ('textoInformação', models.CharField(max_length=2000, verbose_name='textoInformação')),
                ('valorDefault', models.IntegerField(verbose_name='Default')),
                ('valorMin', models.IntegerField(verbose_name='Min')),
                ('valorMax', models.IntegerField(verbose_name='Max')),
                ('comandoGRBL', models.CharField(max_length=100, verbose_name='comandoGRBL')),
            ],
        ),
    ]
