# Generated by Django 4.0.4 on 2022-10-23 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBolas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeLance', models.CharField(max_length=30, verbose_name='Nome do lance')),
                ('anguloX', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Angulo em X')),
                ('anguloY', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Angulo em Y')),
                ('anguloInclinacao', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Angulo de inclinação')),
                ('velocidadeRoloEsq', models.SmallIntegerField(default=0, verbose_name='Velocidade do rolo esquerdo')),
                ('velocidadeRoloDir', models.SmallIntegerField(default=0, verbose_name='Velocidade do rolo direito')),
            ],
        ),
        migrations.CreateModel(
            name='treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeTreino', models.CharField(max_length=20, verbose_name='Nome do Treino')),
                ('Qt_bolas_lance', models.IntegerField(default=5, verbose_name='Bolas lançadas por lance')),
                ('maxBolasTreino', models.IntegerField(default=200, verbose_name='Maximo de bolas por treino')),
                ('cadenciaTreino', models.IntegerField(choices=[(4, 'Baixa'), (3, 'Media'), (2, 'Alta'), (1, 'Elevada')], default=1, verbose_name='Cadencia do treino')),
                ('dataCriacao', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='Data')),
                ('tempoTreino', models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='Tempo de treino(H,MIN)')),
                ('SequenciaLances', models.IntegerField(choices=[(1, 'Aleatoria'), (2, 'Sequencial')], default=1, verbose_name='Sequencia de lances')),
                ('lances', models.ManyToManyField(to='appBolas.lance')),
            ],
        ),
    ]
